[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed0]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed1]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed2]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed3]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed4]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed5]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed6]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed7]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed8]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed9]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed10]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed11]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed12]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed13]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed14]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed15]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed16]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed17]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed18]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed19]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed20]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed21]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed22]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed23]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed24]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed25]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed26]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed27]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed28]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed29]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed30]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed31]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed32]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed33]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=17R
Y=113
Shape=Rectangle 0,0,(10*0.8),(-(113-(10*0.8))*[MeasureAudioSmoothed34]-(10*0.8)),((10*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1